[tasks.build]
args = ["build", "--dev", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]
command = "wasm-pack"
watch = {ignore_pattern = "static/*"}

[tasks.serve]
args = ["-i", "./static/", "-p", "3000", "--nocache", "--try-file", "./static/index.html"]
command = "simple-http-server"
